#!/usr/bin/env ruby

require 'fileutils'; include FileUtils

home_path = Dir.home
current_path = File.expand_path(File.dirname(__FILE__))

black_list = %w!. .. .git .gitignore!
options = {verbose: true}

puts "##############################################"
puts "##                                          ##"
puts "##                                          ##"
puts "##                                          ##"
puts "##                                          ##"
puts "##           SETUP DOTFILES!!!!             ##"
puts "##                                          ##"
puts "##                                          ##"
puts "##                      created by tanaka51 ##"
puts "##                                          ##"
puts "##############################################"
puts ""
puts ""
puts ""
puts "##------------------------------------------##"
puts "## Copy bin/ to $HOME"
puts "##------------------------------------------##"
puts ""
mkdir_p File.join(home_path, 'bin'), options
cd(File.join(current_path, 'bin'), options) do
  (Dir[".*"] - black_list).each do |name|
    cp name, File.join(home_path, 'bin'), options
  end
end

puts ""
puts "##------------------------------------------##"
puts "## Create .tmux.conf"
puts "##------------------------------------------##"
puts ""
loop = true
color = nil
while(loop) do
  puts "Choose tmux color from below."
  puts "  black red blue green yellow oblue magenta [cyan] white"
  print "choose: "
  color = gets.chomp
  color = "cyan" if color.empty?
  loop = !(%w!black red blue green yellow blue magenta cyan white!.include?(color))
end

cd(File.join(current_path, "support"), options) do
  command = "ruby tmux_conf_creater -c #{color}"
  puts "exec: " + command
  system command
end

puts ""
puts "##------------------------------------------##"
puts "## Create symlinks to $HOME"
puts "##------------------------------------------##"
puts ""
cd(current_path, options) do |cur_dir|
  (Dir[".*"] - black_list).each do |name|
    target = File.join(cur_dir, name)
    if File.exists? target
      puts "skip: #{target} exists"
    else
      ln_s target, home_path, options
    end
  end
end

# vim:filetype=ruby

